---
- hosts: all
  become: true
  connection: local
  user: vagrant
  tasks:
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - httpd-tools
        - php