- name: install mariadb-package
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - mariadb
      - mariadb-server
- name: service run mariadb
  service: name=mariadb  state=started enabled=yes